### ISSUE TITLE
无法连接，启动报错

### ISSUE THREAD

**Issue by Theseven87** [ruur/egg-udp#1]
完全按照文档书写，但是程序启动后会报错，uDP没有连接成功
{ Error: write ENOTSUP
    at ChildProcess.target._send (internal/child_process.js:741:20)
    at ChildProcess.target.send (internal/child_process.js:625:19)
    at sendHelper (internal/cluster/utils.js:25:15)
    at send (internal/cluster/master.js:356:10)
    at handle.add (internal/cluster/master.js:328:5)
    at SharedHandle.add (internal/cluster/shared_handle.js:29:3)
    at queryServer (internal/cluster/master.js:317:10)
    at Worker.onmessage (internal/cluster/master.js:253:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at ChildProcess.emit (events.js:187:15) errno: 'ENOTSUP', code: 'ENOTSUP', syscall: 'write' }
不知道是什么原因造成的，另外我不适用本插件，自己写udp连接，程序启动后调用方法启动udp连接也会报这个错误。

**Comment by Naeemo** [comment]
> 另外我不适用本插件，自己写udp连接，程序启动后调用方法启动udp连接也会报这个错误

这应该能证明跟`egg-udp`没关系，可以先尝试不用的情况下定位问题

**Comment by Theseven87** [comment]
非常感谢您的回复；我是新创建了egg项目，然后使用本插件后报错，程序依然在运行，控制台没有UDP连接的打印，我用另一个测试程序发送udp消息也没有接收到。但是把插件相关的东西删除掉就好了。不知道会不会是因为egg版本或者其他模块版本的差异所导致的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Naeemo"<notifications@github.com&gt;; 
发送时间: 2020年3月24日(星期二) 上午9:03
收件人: "ruur/egg-udp"<egg-udp@noreply.github.com&gt;; 
抄送: "董沫"<113552669@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ruur/egg-udp] 无法连接，启动报错 (#1)





  
另外我不适用本插件，自己写udp连接，程序启动后调用方法启动udp连接也会报这个错误
  
这应该能证明跟egg-udp没关系，可以先尝试不用的情况下定位问题

**Comment by ruur** [comment]
@Theseven87 我也起了一个`egg`的新项目，但是没有重现你的问题，由于本人用的`ts`，而`egg`本身是`js`项目，现提供一个`js`版本的example，稍后我会更新到README。代码如下：
```
module.exports = app => {
  return {
    async handle(udp) {
      udp.on('error', (err) => {
        console.log(`udp error:\n${err.stack}`);
      });

      udp.on('message', (msg, rinfo) => {
        console.log(`udp server got: ${msg.toString()} from ${rinfo.address}:${rinfo.port}`);
      });

      udp.on('listening', () => {
        const address = udp.address();
        console.log(`udp listening ${address.address}:${address.port}`);
      });
    },
  };
};
```

测试结果如下： 
<img width="733" alt="test" src="https://user-images.githubusercontent.com/8519222/79416289-e683fc00-7fe1-11ea-9f15-849cfa525c08.png">

**Comment by renjie35** [comment]
我也遇到了,应该是udp在windows环境下会触发这个Error: write ENOTSUP
linux下好像没问题

**Comment by cnkoala** [comment]
这是一个极其坑的问题：在dgram某个版本后，就取消了对windows的正式支持。[See this](https://github.com/nodejs/node/blob/master/test/parallel/test-cluster-dgram-2.js#L11)
~~~
const common = require('../common');
if (common.isWindows)
  common.skip('dgram clustering is currently not supported on Windows.');
~~~

但是，解决的方法还是有的，就是在bind时引入exclusive属性，如：
`udp.bind({port: 1900, exclusive: true})`
[解决方案的链接](https://stackoverflow.com/questions/39253637/how-to-run-node-cluster-on-windows)

相应的代码可能需要修改。

**Comment by ruur** [comment]
#2

**Comment by ruur** [comment]
fix bug: udp is not working on Windows #2
